'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const PKG=path.resolve(__dirname,'..'),VERSION=require('../package.json').version;
const ACTIONS=new Set('edit write test build commit query decision fix milestone rename delete note hook'.split(' '));
const RESULTS=new Set('success failure wall blocked retry unknown'.split(' '));
const VA={E:'edit',W:'write',T:'test',B:'build',C:'commit',Q:'query',D:'decision',F:'fix',M:'milestone','R*':'rename',X:'delete'};
const VR={'✓':'success','✗':'failure','⚠':'wall','⏳':'blocked','↻':'retry','?':'unknown'};
function args(xs){let o={_:[]};for(let i=0;i<xs.length;i++){let x=xs[i];if(!x.startsWith('--'))o._.push(x);else{let [k,v]=x.slice(2).split(/=(.*)/s);o[k]=v!==undefined?v:(xs[i+1]&&!xs[i+1].startsWith('--')?xs[++i]:true)}}return o}
const sleep=ms=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);
function mkdirRaw(d){fs.mkdirSync(d,{recursive:true,mode:0o700});try{fs.chmodSync(d,0o700)}catch{}}
function atomicRaw(f,s){mkdirRaw(path.dirname(f));let t=`${f}.${process.pid}.${crypto.randomUUID()}.tmp`;try{fs.writeFileSync(t,s,{mode:0o600});fs.renameSync(t,f);try{fs.chmodSync(f,0o600)}catch{}}finally{try{fs.rmSync(t,{force:true})}catch{}}}
function text(v,n){if(v==null)return;return String(v).replace(/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/gi,'[REDACTED]').replace(/\b(?:gh[pousr]_[\w]{20,}|sk-(?:proj-)?[\w-]{16,}|xox[baprs]-[\w-]{10,}|AKIA[A-Z0-9]{16}|AIza[\w-]{20,}|eyJ[\w-]{10,}\.[\w-]{10,}\.[\w-]{10,})\b/g,'[REDACTED]').replace(/\b(?:authorization|proxy-authorization|cookie|set-cookie|api[_-]?key|password|passwd|secret|token)\b\s*[:=]?\s*(?:bearer\s+)?[^\s,;]+/gi,'[REDACTED]').replace(/\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|amqp):\/\/[^\s]+/gi,'[REDACTED]').replace(/\bhttps?:\/\/[^\s/@:]+:[^\s/@]+@[^\s]+/gi,'[REDACTED]').replace(/[\x00-\x1f\x7f]+/g,' ').replace(/\s+/g,' ').trim().slice(0,n)}
const stamp=v=>{let d=v?new Date(v):new Date();return Number.isNaN(+d)?new Date().toISOString():d.toISOString()};
function canonical(start){return fs.realpathSync.native(path.resolve(start))}
function project(start=process.cwd()){let origin=canonical(start),p=origin,git=null;while(true){let jj=path.join(p,'.journal');if(fs.existsSync(jj)){rejectLink(jj);return p}if(!git&&fs.existsSync(path.join(p,'.git')))git=p;let q=path.dirname(p);if(q===p)return git||origin;p=q}}
const j=r=>path.join(r,'.journal');
function rejectLink(p){let s=fs.lstatSync(p);if(s.isSymbolicLink())throw Error(`controlled path is a symlink or reparse point: ${p}`);return s}
function assertTree(root){root=canonical(root);let base=j(root);if(!fs.existsSync(base))return;let walk=p=>{let s;try{s=rejectLink(p)}catch(e){if(e.code==='ENOENT')return;throw e}if(s.isDirectory()){let ns;try{ns=fs.readdirSync(p)}catch(e){if(e.code==='ENOENT')return;throw e}for(let n of ns)walk(path.join(p,n))}};walk(base)}
function jp(root,...parts){root=canonical(root);let base=j(root),q=path.resolve(base,...parts);if(q!==base&&!q.startsWith(base+path.sep))throw Error('controlled path escapes .journal');let cur=base;if(fs.existsSync(cur))rejectLink(cur);for(let rel of path.relative(base,q).split(path.sep).filter(Boolean)){cur=path.join(cur,rel);if(fs.existsSync(cur))rejectLink(cur)}return q}
function jmkdir(root,...parts){let q=jp(root,...parts),base=j(canonical(root));if(!fs.existsSync(base)){fs.mkdirSync(base,{mode:0o700});rejectLink(base)}let rel=path.relative(base,q).split(path.sep).filter(Boolean),cur=base;for(let p of rel){cur=path.join(cur,p);if(!fs.existsSync(cur))fs.mkdirSync(cur,{mode:0o700});rejectLink(cur)}return q}
function jread(root,rel,def){let f=jp(root,rel);try{return fs.readFileSync(f,'utf8')}catch(e){if(def!==undefined&&e.code==='ENOENT')return def;throw e}}
function jjson(root,rel,def=null){try{return JSON.parse(jread(root,rel))}catch(e){if(def!==undefined)return def;throw e}}
function jatomic(root,rel,s){let f=jp(root,rel);jmkdir(root,path.dirname(rel));let t=jp(root,`${rel}.${process.pid}.${crypto.randomUUID()}.tmp`);try{fs.writeFileSync(t,s,{mode:0o600});fs.renameSync(t,f);try{fs.chmodSync(f,0o600)}catch{}}finally{try{if(fs.existsSync(t))fs.rmSync(t,{force:true})}catch{}}}
function contained(root,p){let q=path.resolve(root,p),probe=q;while(!fs.existsSync(probe)){let x=path.dirname(probe);if(x===probe)break;probe=x}try{let rr=canonical(root),real=canonical(probe);return real===rr||real.startsWith(rr+path.sep)}catch{return false}}
function event(x,root=process.cwd()){x=x&&typeof x==='object'&&!Array.isArray(x)?x:{};root=canonical(root);let a=VA[x.a]||x.action||'note',r=VR[x.r]||x.result||'unknown',e={schema:2,id:text(x.id,80)||crypto.createHash('sha256').update(JSON.stringify(x)+stamp(x.time||x.t)).digest('hex').slice(0,32),time:stamp(x.time||x.t),provider:['codex','claude','manual','unknown'].includes(x.provider)?x.provider:'manual',session_id:text(x.session_id||process.env.CODEX_SESSION_ID||process.env.CLAUDE_SESSION_ID,80)||'unknown',actor:['agent','human','hook','migration'].includes(x.actor)?x.actor:(x.t?'migration':'human'),action:ACTIONS.has(a)?a:'note',result:RESULTS.has(r)?r:'unknown'};let p=text(x.path||x.f,300);if(p){let raw=p.replace(/:\d+(?::\d+)?$/,'');e.path=(!path.isAbsolute(raw)&&!/^[A-Za-z]:[\\/]/.test(raw)&&contained(root,raw))?p.replace(/\\/g,'/'):'[external]'}for(let [k,v,n] of [['summary',x.summary||x.w,240],['error',x.error||x.e,240],['fix',x.fix,160],['tag',x.tag,80]]){v=text(v,n);if(v)e[k]=v}let ms=Number(x.duration_ms??x.ms);if(Number.isFinite(ms)&&ms>=0)e.duration_ms=Math.min(Math.round(ms),86400000);return e}
function lock(root,wait=1500){assertTree(root);jmkdir(root);let f=jp(root,'.lock'),end=Date.now()+wait;while(true){try{fs.mkdirSync(f,{mode:0o700});fs.writeFileSync(jp(root,'.lock','owner.json'),JSON.stringify({pid:process.pid,time:new Date().toISOString()}),{mode:0o600});return()=>{assertTree(root);fs.rmSync(jp(root,'.lock'),{recursive:true,force:true})}}catch(e){if(e.code!=='EEXIST')throw e;try{rejectLink(f);let o;try{o=JSON.parse(jread(root,path.join('.lock','owner.json')))}catch{}let st=fs.statSync(f),parsed=o?.time?+new Date(o.time):NaN,age=Date.now()-(Number.isFinite(parsed)?parsed:st.mtimeMs),alive=false;if(Number.isInteger(o?.pid)&&o.pid>0){try{process.kill(o.pid,0);alive=true}catch(x){alive=x.code==='EPERM'}}if(age>30000&&!alive){fs.rmSync(jp(root,'.lock'),{recursive:true,force:true});continue}}catch(x){if(x.code==='ENOENT')continue;throw x}if(Date.now()>=end)return null;sleep(25)}}}
function rootFile(root,name){root=canonical(root);let f=path.resolve(root,name);if(f!==root&&!f.startsWith(root+path.sep))throw Error('root file escapes project');if(fs.existsSync(f)){let st=rejectLink(f);if(!st.isFile())throw Error(`${name} must be a regular file`);let real=canonical(f);if(!real.startsWith(root+path.sep))throw Error(`${name} escapes project`)}else{let parent=canonical(path.dirname(f));if(parent!==root)throw Error(`${name} parent escapes project`)}return f}
function ignore(root){let f=rootFile(root,'.gitignore'),s=fs.existsSync(f)?fs.readFileSync(f,'utf8'):'';if(!s.split(/\r?\n/).some(x=>x.trim()==='.journal/'))fs.appendFileSync(f,(s&&!s.endsWith('\n')?'\n':'')+'.journal/\n',{mode:0o600})}
function init(root){root=canonical(root);if(fs.existsSync(j(root)))assertTree(root);jmkdir(root,'pending');jmkdir(root,'quarantine');for(let n of ['GLYPH.md','INDEX.md'])if(!fs.existsSync(jp(root,n))){fs.copyFileSync(path.join(PKG,'skills','silex','templates',n),jp(root,n));try{fs.chmodSync(jp(root,n),0o600)}catch{}}if(!fs.existsSync(jp(root,'timeline.jsonl')))fs.writeFileSync(jp(root,'timeline.jsonl'),'',{mode:0o600});ignore(root);rebuild(root);return j(root)}
function files(root){assertTree(root);return fs.readdirSync(jp(root)).filter(x=>/^timeline(?:-.+)?\.jsonl$/.test(x)&&!x.includes('v1-backup')).sort((a,b)=>a==='timeline.jsonl'?1:b==='timeline.jsonl'?-1:a.localeCompare(b))}
function events(root){root=canonical(root);let z=[],seen=new Set,corrupt=[];if(!fs.existsSync(j(root)))return z;for(let n of files(root))for(let [i,l] of jread(root,n).split(/\r?\n/).entries()){try{if(l.trim()){let e=event(JSON.parse(l),root);if(!seen.has(e.id)){seen.add(e.id);z.push(e)}}}catch{corrupt.push(`${n}:${i+1}`)}}if(corrupt.length)throw Error(`corrupt timeline records: ${corrupt.join(', ')}`);return z.sort((a,b)=>a.time.localeCompare(b.time))}
function quarantine(root,rel,reason){jmkdir(root,'quarantine');let src=jp(root,rel),name=`${Date.now()}-${crypto.randomUUID()}-${path.basename(rel)}.bad`;fs.renameSync(src,jp(root,'quarantine',name));jatomic(root,path.join('quarantine',name+'.reason'),text(reason,160)+'\n')}
function drain(root,es){let seen=new Set(es.map(e=>e.id)),add=[],bad=0;jmkdir(root,'pending');for(let n of fs.readdirSync(jp(root,'pending')).filter(x=>x.endsWith('.json')).sort()){let rel=path.join('pending',n),v;try{v=JSON.parse(jread(root,rel));if(!v||typeof v!=='object'||Array.isArray(v))throw Error('not an object');let e=event(v,root);if(!seen.has(e.id)){seen.add(e.id);add.push(e)}fs.rmSync(jp(root,rel),{force:true})}catch(e){bad++;quarantine(root,rel,e.message)}}return{add,bad}}
function health(root){if(!fs.existsSync(j(root)))return{pending:0,quarantined:0};assertTree(root);let count=d=>fs.existsSync(jp(root,d))?fs.readdirSync(jp(root,d)).filter(n=>!n.endsWith('.reason')).length:0;return{pending:count('pending'),quarantined:count('quarantine')}}
function state(root,es){let recent=es.slice(-5),last=recent.at(-1),pick=e=>e&&Object.fromEntries(['time','action','result','path','summary','tag'].filter(k=>e[k]!=null).map(k=>[k,e[k]]));return{schema:2,project:path.basename(root),updated_at:new Date().toISOString(),count_total:es.length,last:pick(last),recent:recent.map(pick),health:health(root)}}
function markdown(s){let line=e=>`${e.time} | ${e.action} | ${e.result}${e.path?' | '+e.path:''}${e.summary?' | '+e.summary:''}`;return`# ${s.project}\n\nGenerated from validated Silex events. Do not edit.\n\n- updated: ${s.updated_at}\n- events: ${s.count_total}\n- pending: ${s.health.pending}\n- quarantined: ${s.health.quarantined}\n- last: ${s.last?line(s.last):'<none>'}\n\n## Recent\n${s.recent.length?s.recent.map(e=>'- '+line(e)).join('\n'):'<none>'}\n`}
function rebuild0(root){let es=events(root),d=drain(root,es);if(d.add.length){fs.appendFileSync(jp(root,'timeline.jsonl'),d.add.map(JSON.stringify).join('\n')+'\n',{mode:0o600});es.push(...d.add);es.sort((a,b)=>a.time.localeCompare(b.time))}let s=state(root,es);jatomic(root,'STATE.json',JSON.stringify(s,null,2)+'\n');jatomic(root,'STATE.md',markdown(s));jatomic(root,'INDEX.md','# Milestones\n\n'+es.filter(e=>e.action==='milestone').map(e=>`${e.time} | ${e.tag||e.summary||'milestone'}`).join('\n')+'\n');return s}
function rebuild(root){root=project(root);let u=lock(root);if(!u)throw Error('journal is busy');try{return rebuild0(root)}finally{u()}}
function rotate0(root,force=false){let f=jp(root,'timeline.jsonl'),max=Number(process.env.SILEX_ROTATE_BYTES||10485760);if(!fs.existsSync(f)||(!force&&fs.statSync(f).size<max))return null;let s=new Date().toISOString().replace(/[:.]/g,'-'),n=0,d;do{d=jp(root,`timeline-${s}${n?'-'+n:''}.jsonl`);n++}while(fs.existsSync(d));fs.renameSync(f,d);try{fs.chmodSync(d,0o600)}catch{}fs.writeFileSync(f,'',{mode:0o600});return d}
function append(root,x,opt={}){root=project(root);if(!fs.existsSync(j(root)))init(root);assertTree(root);let e=event(x,root),u=lock(root,Number(opt.wait||1500));if(!u){let rel=path.join('pending',`${Date.now()}-${process.pid}-${crypto.randomUUID()}.json`);jatomic(root,rel,JSON.stringify(e));return{status:'pending',event:e,file:jp(root,rel)}}try{rotate0(root);let es=events(root),d=drain(root,es),drained=d.add.length,all=[...d.add];if(!new Set(es.concat(all).map(v=>v.id)).has(e.id))all.push(e);if(all.length)fs.appendFileSync(jp(root,'timeline.jsonl'),all.map(JSON.stringify).join('\n')+'\n',{mode:0o600});rebuild0(root);return{status:'appended',event:e,drained,quarantined:d.bad}}finally{u()}}
function rotate(root){root=project(root);let u=lock(root);if(!u)throw Error('journal is busy');try{return rotate0(root,true)}finally{u()}}
function resume(root){root=project(root);if(!fs.existsSync(j(root)))return null;rebuild(root);let s=jjson(root,'STATE.json');if(!s||s.schema!==2)return null;let clean=e=>e&&{time:stamp(e.time),action:ACTIONS.has(e.action)?e.action:'note',result:RESULTS.has(e.result)?e.result:'unknown',...(e.path?{path:text(e.path,300)}:{}),...(e.summary?{summary:text(e.summary,240)}:{}),...(e.tag?{tag:text(e.tag,80)}:{})};return{schema:2,project:text(s.project,100),updated_at:stamp(s.updated_at),count_total:Math.max(0,Number(s.count_total)||0),last:clean(s.last),recent:Array.isArray(s.recent)?s.recent.slice(-5).map(clean).filter(Boolean):[],health:health(root)}}
function toolOutcome(input){let sources=[input?.tool_response,input?.toolResponse,input?.result].filter(x=>x&&typeof x==='object'&&!Array.isArray(x));for(let x of sources){if((x.error!=null&&x.error!==false&&x.error!=='')||x.is_error===true||x.success===false)return'failure';if(x.exit_code!=null&&Number.isFinite(Number(x.exit_code))&&Number(x.exit_code)!==0)return'failure';let v=String(x.status??x.outcome??'').toLowerCase();if(/^(failure|failed|error|blocked)$/.test(v))return'failure'}for(let x of sources){if(x.success===true||x.is_error===false||(x.exit_code!=null&&Number(x.exit_code)===0))return'success';let v=String(x.status??x.outcome??'').toLowerCase();if(/^(success|succeeded|ok|completed)$/.test(v))return'success'}return'unknown'}
function toolEvent(input,provider,root){if(!input||typeof input!=='object')return null;let name=text(input.tool_name||input.toolName||input.tool||input.name,60);if(!name||/silex/i.test(name))return null;let p=input.tool_input?.path||input.tool_input?.file_path||input.input?.path||input.input?.file_path||input.path,kind=/test/i.test(name)?'test':/build|compile/i.test(name)?'build':/write|edit|patch/i.test(name)?'edit':/read|search|grep|glob/i.test(name)?'query':'hook';return event({provider,actor:'hook',action:kind,result:toolOutcome(input),path:p,duration_ms:input.duration_ms},root)}
function hook(kind,cwd,input={},provider='claude'){let root=project(cwd);if(!fs.existsSync(j(root)))return JSON.stringify({});if(/posttooluse/i.test(kind)){let e=toolEvent(input,provider,root);if(e)append(root,e);return JSON.stringify({})}if(!/sessionstart|precompact|stop/i.test(kind))return JSON.stringify({});if(!/sessionstart/i.test(kind)){rebuild(root);return JSON.stringify({})}let s=resume(root),body=JSON.stringify(s).replace(/</g,'\\u003c').replace(/>/g,'\\u003e'),context=`<silex-resume-untrusted format="json" schema="2">\n${body}\n</silex-resume-untrusted>`;return JSON.stringify({...(provider==='codex'?{continue:true}:{}),hookSpecificOutput:{hookEventName:'SessionStart',additionalContext:context}})}
function copy(a,b){fs.mkdirSync(b,{recursive:true});for(let e of fs.readdirSync(a,{withFileTypes:true})){let x=path.join(a,e.name),y=path.join(b,e.name);e.isDirectory()?copy(x,y):fs.copyFileSync(x,y)}}
const base=(t,h)=>path.join(h,t==='codex'?'.codex':'.claude'),managed=x=>String(x?.command||'').includes('--managed-by=silex-v2'),legacy=x=>/\.journal[\\/]STATE\.md/.test(String(x?.command||''))&&/(Get-Content|cat |readFileSync)/.test(String(x.command));
function cleanEntries(xs,removeLegacy=false){let out=[];for(let e of Array.isArray(xs)?xs:[]){let hooks=(Array.isArray(e.hooks)?e.hooks:[]).filter(x=>!managed(x)&&!(removeLegacy&&legacy(x)));if(hooks.length)out.push({...e,hooks})}return out}
function installPath(b,p){b=path.resolve(b);p=path.resolve(p);if(p!==b&&!p.startsWith(b+path.sep))throw Error('provider path escapes its base');if(fs.existsSync(b))rejectLink(b);let cur=b;for(let part of path.relative(b,p).split(path.sep).filter(Boolean)){cur=path.join(cur,part);if(fs.existsSync(cur))rejectLink(cur)}return p}
function injected(name){if(process.env.SILEX_INSTALL_FAIL===name)throw Error(`injected install failure: ${name}`)}
function rollbackInstall(x){let errors=[],run=(name,fn)=>{try{if(process.env.SILEX_ROLLBACK_FAIL===name)throw Error(`injected rollback failure: ${name}`);fn()}catch(e){errors.push(new Error(`rollback ${name} failed: ${e.message}`,{cause:e}))}};run('skill',()=>{fs.rmSync(x.skill,{recursive:true,force:true});if(x.hadSkill&&fs.existsSync(path.join(x.backup,'skill'))){mkdirRaw(path.dirname(x.skill));fs.renameSync(path.join(x.backup,'skill'),x.skill)}});run('runtime',()=>{fs.rmSync(x.runtimeDir,{recursive:true,force:true});if(x.hadRuntime&&fs.existsSync(path.join(x.backup,'runtime')))fs.renameSync(path.join(x.backup,'runtime'),x.runtimeDir)});run('config',()=>{if(x.hadConfig)fs.copyFileSync(path.join(x.backup,'config'),x.config);else fs.rmSync(x.config,{force:true})});return errors}
function install(t,h=os.homedir()){
  if(!['codex','claude'].includes(t))throw Error('target must be codex or claude');
  h=path.resolve(h);let b=base(t,h),skill=path.join(b,'skills','silex'),runtimeDir=path.join(b,'silex'),runtime=path.join(runtimeDir,'bin','silex.js'),config=path.join(b,t==='codex'?'hooks.json':'settings.json'),manifest=path.join(runtimeDir,'install-manifest.json');
  mkdirRaw(b);for(let p of [skill,runtimeDir,config])installPath(b,p);
  let before=fs.existsSync(config)?fs.readFileSync(config,'utf8'):null,d=before?JSON.parse(before):{};
  if(!d||typeof d!=='object'||Array.isArray(d))throw Error('provider config must be an object');
  d.hooks=d.hooks&&typeof d.hooks==='object'&&!Array.isArray(d.hooks)?d.hooks:{};
  for(let kind of ['SessionStart','PostToolUse','PreCompact','Stop']){d.hooks[kind]=cleanEntries(d.hooks[kind],kind==='SessionStart');let cmd=`${JSON.stringify(process.execPath)} ${JSON.stringify(runtime)} hook ${kind} --provider ${t} --managed-by=silex-v2`;d.hooks[kind].push({...(kind==='SessionStart'?{matcher:t==='codex'?'startup|resume|clear':'*'}:{}),hooks:[{type:'command',command:cmd}]})}
  let stage=path.join(b,`.silex-stage-${crypto.randomUUID()}`),backup=path.join(b,`.silex-backup-${crypto.randomUUID()}`),hadSkill=fs.existsSync(skill),hadRuntime=fs.existsSync(runtimeDir),hadConfig=fs.existsSync(config),backedUp=false;
  try{
    copy(path.join(PKG,'skills','silex'),path.join(stage,'skill'));copy(path.join(PKG,'lib'),path.join(stage,'runtime','lib'));mkdirRaw(path.join(stage,'runtime','bin'));fs.copyFileSync(path.join(PKG,'bin','silex.js'),path.join(stage,'runtime','bin','silex.js'));fs.copyFileSync(path.join(PKG,'package.json'),path.join(stage,'runtime','package.json'));
    let stagedSkill=path.join(stage,'skill','SKILL.md'),absoluteCommand=`${JSON.stringify(process.execPath)} ${JSON.stringify(runtime)}`;fs.writeFileSync(stagedSkill,fs.readFileSync(stagedSkill,'utf8').replaceAll('{{SILEX_COMMAND}}',absoluteCommand),{mode:0o600});cp.execFileSync(process.execPath,[path.join(stage,'runtime','bin','silex.js'),'help'],{stdio:'ignore'});
    mkdirRaw(backup);if(hadSkill)fs.renameSync(skill,path.join(backup,'skill'));if(hadRuntime)fs.renameSync(runtimeDir,path.join(backup,'runtime'));if(hadConfig)fs.copyFileSync(config,path.join(backup,'config'));backedUp=true;injected('after-backup');
    mkdirRaw(path.dirname(skill));fs.renameSync(path.join(stage,'skill'),skill);injected('after-skill');
    fs.renameSync(path.join(stage,'runtime'),runtimeDir);injected('after-runtime');
    atomicRaw(config,JSON.stringify(d,null,2)+'\n');injected('after-config');
    let m={schema:1,owner:'silex-v2',version:VERSION,target:t,installed_at:new Date().toISOString()};atomicRaw(manifest,JSON.stringify(m,null,2)+'\n');injected('after-manifest');
    let check=status(t,h);if(!check.installed||!check.skill||!check.runtime||!check.hook)throw Error('installation verification failed');
    fs.rmSync(stage,{recursive:true,force:true});fs.rmSync(backup,{recursive:true,force:true});return m;
  }catch(promotion){
    let rollback=backedUp?rollbackInstall({skill,runtimeDir,config,backup,hadSkill,hadRuntime,hadConfig}):[];
    try{fs.rmSync(stage,{recursive:true,force:true})}catch(e){rollback.push(new Error(`rollback staging cleanup failed: ${e.message}`,{cause:e}))}
    if(rollback.length)throw new AggregateError([promotion,...rollback],`Silex install failed and rollback was incomplete. Recovery backup retained at: ${backup}`);
    fs.rmSync(backup,{recursive:true,force:true});throw promotion;
  }
}
function exact(t,h){let b=base(t,path.resolve(h)),skill=path.join(b,'skills','silex'),runtime=path.join(b,'silex'),config=path.join(b,t==='codex'?'hooks.json':'settings.json');return{b,skill,runtime,config,manifest:path.join(runtime,'install-manifest.json')}}
function ownedDir(p,parent){installPath(parent,p);return true}
function status(t,h=os.homedir()){let x=exact(t,h),m;try{m=JSON.parse(fs.readFileSync(x.manifest,'utf8'))}catch{return{target:t,installed:false}}let d={};try{d=JSON.parse(fs.readFileSync(x.config,'utf8'))}catch{}let legacyFound=(d.hooks?.SessionStart||[]).some(e=>(e.hooks||[]).some(legacy)),kinds=['SessionStart','PostToolUse','PreCompact','Stop'],hooks=kinds.every(k=>(d.hooks?.[k]||[]).flatMap(e=>e.hooks||[]).filter(managed).length===1),owned=m.owner==='silex-v2'&&ownedDir(x.runtime,x.b)&&ownedDir(x.skill,x.b);return{target:t,installed:owned,version:m.version,skill:owned&&fs.existsSync(path.join(x.skill,'SKILL.md')),runtime:owned&&fs.existsSync(path.join(x.runtime,'bin','silex.js'))&&(()=>{try{cp.execFileSync(process.execPath,[path.join(x.runtime,'bin','silex.js'),'help'],{stdio:'ignore'});return true}catch{return false}})(),hook:hooks&&!legacyFound,legacy:legacyFound}}
function uninstall(t,h=os.homedir()){let x=exact(t,h);for(let p of [x.runtime,x.skill,x.config])installPath(x.b,p);let m;try{m=JSON.parse(fs.readFileSync(x.manifest,'utf8'))}catch{return false}if(m.owner!=='silex-v2')throw Error('untrusted install');let d={};try{d=JSON.parse(fs.readFileSync(x.config,'utf8'))}catch{throw Error('provider config is invalid')}for(let k of Object.keys(d.hooks||{}))d.hooks[k]=cleanEntries(d.hooks[k]);atomicRaw(x.config,JSON.stringify(d,null,2)+'\n');fs.rmSync(x.skill,{recursive:true,force:true});fs.rmSync(x.runtime,{recursive:true,force:true});return true}
function migrate(root){root=project(root);let src=jp(root,'timeline.jsonl'),es=[],bad=[];for(let [i,l] of fs.readFileSync(src,'utf8').split(/\r?\n/).entries())try{if(l.trim())es.push(event(JSON.parse(l),root))}catch{bad.push(i+1)}if(bad.length)throw Error(`migration refused: corrupt records at lines ${bad.join(', ')}`);let u=lock(root);if(!u)throw Error('journal is busy');try{let bak=`timeline-v1-backup-${Date.now()}.jsonl`;fs.copyFileSync(src,jp(root,bak));try{fs.chmodSync(jp(root,bak),0o600)}catch{}jatomic(root,'timeline.jsonl',es.map(JSON.stringify).join('\n')+(es.length?'\n':''));rebuild0(root);return{events:es.length,backup:jp(root,bak)}}finally{u()}}
async function stdin(){if(process.stdin.isTTY)return{};let z='';for await(let c of process.stdin)z+=c;if(!z.trim())return{};try{return JSON.parse(z)}catch{return{}}}
async function main(argv,io={out:s=>process.stdout.write(s)}){let a=args(argv),c=a._[0]||'install',home=path.resolve(a.home||os.homedir()),ts=(a.target||(a._.length?'both':'claude')).split(',').flatMap(x=>x==='both'?['codex','claude']:[x]),root=project(path.resolve(a.cwd||process.cwd())),r;if(c==='help'){io.out(`Silex ${VERSION}\nCommands: install status doctor uninstall init append log mark state rebuild rotate migrate hook\n`);return}if(c==='install')r=ts.map(t=>install(t,home));else if(c==='status'||c==='doctor'){r=ts.map(t=>status(t,home));if(fs.existsSync(j(root))){let journal=resume(root)?.health;for(let x of r)x.journal=journal}if(c==='doctor'&&r.some(x=>!x.installed||!x.skill||!x.runtime||!x.hook))process.exitCode=1}else if(c==='uninstall')r=ts.map(t=>({target:t,removed:uninstall(t,home)}));else if(c==='init')r={journal:init(root)};else if(c==='append'||c==='log')r=append(root,{action:c==='log'?'note':a.action,result:a.result||'unknown',path:a.path,summary:a.summary||a._.slice(1).join(' '),error:a.error,fix:a.fix,tag:a.tag,provider:a.provider||'manual',actor:a.actor||'human',duration_ms:a.duration_ms});else if(c==='mark'){let label=a._.slice(1).join(' ')||a.tag;if(!label)throw Error('mark requires label');r=append(root,{action:'milestone',result:'success',tag:label,summary:a.summary})}else if(c==='state')r=resume(root);else if(c==='rebuild')r=rebuild(root);else if(c==='rotate')r={rotated:rotate(root)};else if(c==='migrate')r=migrate(root);else if(c==='hook'){io.out(hook(a._[1]||'SessionStart',root,await stdin(),a.provider||'codex'));return}else throw Error(`unknown command: ${c}`);io.out(JSON.stringify(r,null,2)+'\n')}
module.exports={main,args,event,text,project,init,append,events,rebuild,rotate,resume,hook,toolEvent,health,install,status,uninstall,migrate};
